export const SET_PROJECT_STATUS = 'SET_PROJECT_STATUS';
export const SET_PROJECT_TYPE = 'SET_PROJECT_TYPE';
export const SET_PROJECT_TYPE_ALL = 'SET_PROJECT_TYPE_ALL';
export const SET_TOKEN_TYPE = 'SET_TOKEN_TYPE';
export const SET_TOKEN_TYPE_ALL = 'SET_TOKEN_TYPE_ALL';
export const SET_CONDITIONS_TYPE = 'SET_CONDITIONS_TYPE';
export const SET_VOLUME_STATUS = 'SET_VOLUME_STATUS';
export const SET_CLEAR = 'SET_CLEAR';
