export const data = [
  {
    id: 1,
    name: 'Pyshky.net',
    status: 'green',
    type: 'TRST',
    conditions: 'x2,6 months',
    volume: 120000,
    roi: 4,
    free: 20,
    hedge: 20,
  },
  {
    id: 2,
    name: 'NFT-Flowershop',
    status: 'yellow',
    type: 'THT',
    conditions: 'x4,2 years',
    volume: 80000,
    roi: 23,
    free: 12,
    hedge: 0,
  },
  {
    id: 3,
    name: 'Tokenhunt.club',
    status: 'green',
    type: 'THC',
    conditions: 'x2,1 year',
    volume: 120000,
    roi: 23,
    free: 2,
    hedge: 20,
  },
  {
    id: 4,
    name: 'Web3 P2P University',
    status: 'red',
    type: 'TRST',
    conditions: 'x5,3 years',
    volume: 400000,
    roi: 6,
    free: 1,
    hedge: 0,
  },
  {
    id: 5,
    name: 'KnownOriginNFT',
    status: 'yellow',
    type: 'THC',
    conditions: 'x3,0 mounts',
    volume: 250000,
    roi: 12,
    free: 5,
    hedge: 8,
  },
  {
    id: 6,
    name: 'BakerySwap',
    status: 'red',
    type: 'THT',
    conditions: 'x2,1 years',
    volume: 200000,
    roi: 12,
    free: 1,
    hedge: 0,
  },
  {
    id: 7,
    name: 'Myth Market',
    status: 'green',
    type: 'TRST',
    conditions: 'x1,9 months',
    volume: 95000,
    roi: 4,
    free: 12,
    hedge: 18,
  },
  {
    id: 8,
    name: 'AtomicNFTMarket',
    status: 'yellow',
    type: 'TRST',
    conditions: 'x1,5 years',
    volume: 190000,
    roi: 14,
    free: 5,
    hedge: 16,
  },
  {
    id: 9,
    name: 'SuperRare',
    status: 'yellow',
    type: 'THC',
    conditions: 'x2,1 months',
    volume: 200000,
    roi: 10,
    free: 1,
    hedge: 0,
  },
  {
    id: 10,
    name: 'Rarible',
    status: 'green',
    type: 'TNT',
    conditions: 'x2,5 months',
    volume: 100000,
    roi: 15,
    free: 10,
    hedge: 20,
  },
  {
    id: 11,
    name: 'OpenSea',
    status: 'red',
    type: 'TRST',
    conditions: 'x5,0 years',
    volume: 250000,
    roi: 5,
    free: 2,
    hedge: 10,
  },
  {
    id: 12,
    name: 'NFT-Candyshop',
    status: 'green',
    type: 'TRST',
    conditions: 'x2,1 years',
    volume: 80000,
    roi: 6,
    free: 25,
    hedge: 17,
  },
];

export const popupProjects = {
  type: 'project',
  data: [{ name: 'green' }, { name: 'yellow' }, { name: 'red' }],
};

export const popupConditions = {
  type: 'conditions',
  data: [{ name: '<1 year' }, { name: '<2,5 years' }, { name: '>5 years' }],
};
